class AppAsset {
  AppAsset._();
  static const grid = 'assets/images/grid.svg';
  static const logo = 'assets/images/logo.svg';
  static const google = 'assets/images/google.svg';
  static const apple = 'assets/images/apple.svg';
  static const chat = 'assets/images/chat.svg';
  static const clipboard = 'assets/images/clipboard.svg';
  static const setting = 'assets/images/setting.svg';
  static const users = 'assets/images/users.svg';
  static const pro = 'assets/images/pro.svg';
  static const logout = 'assets/images/logout.svg';
  static const power = 'assets/images/power.svg';
  static const pin = 'assets/images/pin.svg';
  static const send = 'assets/images/send.svg';
  static const aiAvatar = 'assets/images/ai_avatar.svg';
  static const edit = 'assets/images/edit.svg';
  static const copy = 'assets/images/copy.svg';
  static const refresh = 'assets/images/refresh.svg';
  static const like = 'assets/images/like.svg';
  static const dislike = 'assets/images/dislike.svg';
  static const sort = 'assets/images/sort.svg';
  static const delete = 'assets/images/delete.svg';
  static const reset = 'assets/images/reset.svg';
  static const plus = 'assets/images/plus.svg';
  static const filter = 'assets/images/filter.svg';
  static const pdf = 'assets/images/pdf.svg';
  static const pdfGreen = 'assets/images/pdf_green.svg';
  static const date = 'assets/images/date.svg';
  static const cloud = 'assets/images/cloud.svg';
}
